### ISSUE TITLE
Visualizing the model

### ISSUE THREAD

**Issue by openbrian** [EOP-OMB/opal#34]
Not an issue, but I thought I'd share something...

django-extensions is already part of the project.  I ran a few commands and generated an SVG of the model classes.  You'll need graphviz on your machine to run dot.

```shell
python manage.py graph_models -g ssp > opal.dot
dot -T svg opal.dot > opal.svg
```

It's a big image.  Here's a snippet.

![image](https://user-images.githubusercontent.com/2524550/150812291-b54015f5-f30a-43f2-b5c0-c94d21e33974.png)

**Comment by dan-omb** [comment]
Thanks
