### ISSUE TITLE
Open to a PR to streamline usage with Docker?

### ISSUE THREAD

**Issue by wesley-dean-flexion** [EOP-OMB/opal#5]
@dan-omb Hi.  Any interest in a PR to streamline usage with Docker?

* rearrange layers to reduce image build size (1.22GB -> 0.56GB?) and faciliate layer caching for faster rebuilds
* remove extraneous packages added during the build
* cleanup package (apt, pip) install cache
* run as an unprivileged user
* tweak ENTRYPOINT and CMD to make Django play nice with Docker

**Comment by dan-omb** [comment]
Thanks, This was a nice improvement

**Comment by wesley-dean-flexion** [comment]
Glad to help.

For what it's worth, this project came up in a conversation a few days ago with some of my GSA / TTS colleagues.  Another colleague of mine working with NIST / FedRAMP, particularly with regards to the OSCAL component.
